### PR TITLE
docs: clarify docs on ValidateWith and fix documentation errors

### LINKED ISSUE #809: docs: clarify behavior of File.ValidateWith()
ACH Version: `1.5.1`

**Problem**
In the Go library, `File.ValidateWith` will not apply validation options to the underlying batches since `File.ValidateWith` does not modify any state. This is confusing for people using the library who want to apply validation options to the batches.

**Solution**
Update the method's documentation to clarify the behavior. Explain that `File.ValidateWith` will not set validation options for its batches.

### PR DESCRIPTION
**Pull request by vxio**
Fixes #809

### CODE REVIEW

File: file.go [hunk 1]
```diff
@@ -558,7 +558,11 @@ type ValidateOpts struct {
 }
 
 // ValidateWith performs NACHA format rule checks on each record according to their specification
-// overlayed with any custom flags. Any ValidateOpts on the File are ignored, use Validate() instead.
+// overlayed with any custom flags.
+//
+// ValidateOpts set with SetValidation() are ignored, use Validate() instead.
+// ValidationOpts will only be applied to the FileHeader.
```
Comment (nlakritz) [inline file.go]:
```suggestion
// ValidateOpts will only be applied to the FileHeader.
```

**Review by adamdecaf — APPROVED** [review]
