### PR TITLE
remove empty lines in write function

### LINKED ISSUE #1275: IAT Batch EntryDetails with missing Addenda Records output empty lines in resulting file
### ACH Version

1.32.1

### What were you trying to do?

We are trying to reach an input NACHA file that may not always be entirely valid. There is a case when we're reading a NACHA file with an IAT batch with an entry detail that does not have all the required addenda records. We then replace the account numbers in this file with tokenized versions of the original account numbers and then write the file back out. Note that we are skipping all validation on the NACHA file we read in.

### What did you expect to see?

We essentially want this output file to be the exact same as the input file except for the account numbers in each entry detail record. In this case, when we write the corresponding NACHA file back blank lines are added for the missing IAT addenda records. These should not be blank and just omitted from the output NACHA file.

### What did you see?

We see an output NACHA file that looks like this (see input NACHA file in the reproduction steps:

```
5200PAYMENTEX       null                3333333333WEBDEBNCRE   2104052308070131065000090000001
631121000250_qxitKWIfZtGEuz4f0002384606achRpAtddTrackiDavida Gulgowski        1065000090960299
799R02698695708280169      06500009                                            065000090960299
820000000200121000250000000000000000023846063333333333                         065000090000001
5200PAYMENTEX       null                3333333333PPDDEBNCRE   2104052308070131065000090000002
626121000250_qxitKWIfZtGEuz4f0001632681achRpAtddTrackiClotilde Mayer          1065000090960300
799R02758148906847205      06500009                                            065000090960300
820000000200121000250000016326810000000000003333333333                         065000090000002
5200PAYMENTEX       null                3333333333TELDEBNCRE   2104052308070131065000090000003
636121000250_qxitKWIfZtGEuz4f0000567181achRpAtddTrackiMr. Ora Kertzmann       1065000090960301
799R02569987887228789      06500009                                            065000090960301
820000000200121000250000005671810000000000003333333333                         065000090000003
5200PAYMENTEX       ONLINEPAY           3333333333CTXDEBNCRE   2104052308070131065000090000004
631121000250_qxitKWIfZtGEuz4f0000440546achRpAtddTracki0001    Lasonya Boeh    1065000090960302
799R02223739056036789      06500009                                            065000090960302
820000000200121000250000000000000000004405463333333333                         065000090000004
5200PAYMENTEX       null                3333333333CCDDEBNCRE   2104052308070131065000090000005
621121000250_qxitKWIfZtGEuz4f0002319389achRpAtddTrackiEmmett Kutch            1065000090960298
799R02533647136327294      06500009                                            065000090960298
820000000200121000250000000000000000023193893333333333                         065000090000005
5200PAYMENTEX       null                3333333333ARCDEBNCRE   2104052308070131065000090000007
626121000250_qxitKWIfZtGEuz4f0002314634               Adolph Hagenes          1065000090960304
799R02072466791854699      06500009                                            065000090960304
820000000200121000250000023146340000000000003333333333                         065000090000007
5200PAYMENTEX       null                3333333333RCKDEBNCRE   2104052308070131065000090000008
626121000250_qxitKWIfZtGEuz4f0001432130               Blair Brakus V          1065000090960305
799R02566452516503272      06500009                                            065000090960305
820000000200121000250000014321300000000000003333333333                         065000090000008
5200PAYMENTEX       null                3333333333CIEDEBNCRE   2104052308070131065000090000009
621121000250_qxitKWIfZtGEuz4f0000630603achRpAtddTrackiDamion Gottlieb         1065000090960306
799R02407598362669088      06500009                                            065000090960306
820000000200121000250000000000000000006306033333333333                         065000090000009
5200ENDZONE 1       FF3               US3333333333IATDEBNCRE   USDUSD2308070131065000090000006
6311210002500000             000106620300000000000000000000000003752151084    1065000090960303







799R02801938170560934      06500009                                            065000090960303
820000000200121000250000000000000000010662033333333333                         065000090000006
9000009000004000000180108900225000005946626000006841347                                       
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
```

### How can we reproduce the problem?

Read this NACHA file in while skipping all validation. Then try to write this NACHA file back out using `ach.NewWriter(buffer).Write(file)`

```
101 065000090 06500009023080714001094101PAYMENT EXCHANGE PRRT                                 
5200PAYMENTEX       null                3333333333WEBDEBNCRE   2104052308070131065000090000001
631121000250000000037521510840002384606achRpAtddTrackiDavida Gulgowski        1065000090960299
799R02698695708280169      06500009                                            065000090960299
820000000200121000250000000000000000023846063333333333                         065000090000001
5200PAYMENTEX       null                3333333333PPDDEBNCRE   2104052308070131065000090000002
626121000250000000037521510840001632681achRpAtddTrackiClotilde Mayer          1065000090960300
799R02758148906847205      06500009                                            065000090960300
820000000200121000250000016326810000000000003333333333                         065000090000002
5200PAYMENTEX       null                3333333333TELDEBNCRE   2104052308070131065000090000003
636121000250000000037521510840000567181achRpAtddTrackiMr. Ora Kertzmann       1065000090960301
799R02569987887228789      06500009                                            065000090960301
820000000200121000250000005671810000000000003333333333                         065000090000003
5200PAYMENTEX       ONLINEPAY           3333333333CTXDEBNCRE   2104052308070131065000090000004
631121000250000000037521510840000440546achRpAtddTracki0001    Lasonya Boeh    1065000090960302
799R02223739056036789      06500009                                            065000090960302
820000000200121000250000000000000000004405463333333333                         065000090000004
5200PAYMENTEX       null                3333333333CCDDEBNCRE   2104052308070131065000090000005
621121000250000000037521510840002319389achRpAtddTrackiEmmett Kutch            1065000090960298
799R02533647136327294      06500009                                            065000090960298
820000000200121000250000000000000000023193893333333333                         065000090000005
5200ENDZONE 1       FF3               US3333333333IATDEBNCRE   USDUSD2308070131065000090000006
631121000250                 000106620300000000000000000000000003752151084    1065000090960303
799R02801938170560934      06500009                                            065000090960303
820000000200121000250000000000000000010662033333333333                         065000090000006
5200PAYMENTEX       null                3333333333ARCDEBNCRE   2104052308070131065000090000007
626121000250000000037521510840002314634               Adolph Hagenes          1065000090960304
799R02072466791854699      06500009                                            065000090960304
820000000200121000250000023146340000000000003333333333                         065000090000007
5200PAYMENTEX       null                3333333333RCKDEBNCRE   2104052308070131065000090000008
626121000250000000037521510840001432130               Blair Brakus V          1065000090960305
799R02566452516503272      06500009                                            065000090960305
820000000200121000250000014321300000000000003333333333                         065000090000008
5200PAYMENTEX       null                3333333333CIEDEBNCRE   2104052308070131065000090000009
621121000250000000037521510840000630603achRpAtddTrackiDamion Gottlieb         1065000090960306
799R02407598362669088      06500009                                            065000090960306
820000000200121000250000000000000000006306033333333333                         065000090000009
9000009000004000000180108900225000005946626000006841347                                       
```

### PR DESCRIPTION
**Pull request by mfdeveloper508**
Fixes: https://github.com/moov-io/ach/issues/1275

### CODE REVIEW

File: fileHeader.go [hunk 1]
```diff
@@ -160,7 +160,7 @@ func trimRoutingNumberLeadingZero(s string) string {
 }
 
 // String writes the FileHeader struct to a 94 character string.
-func (fh *FileHeader) String() string {
+func (fh FileHeader) String() string {
```
Comment (adamdecaf) [inline fileHeader.go]: Why make this change? It could have a performance impact.

**Review by adamdecaf — APPROVED** [review]

**Review by wadearnold — APPROVED** [review]
Thanks for adding the test case @adamdecaf and the code changes @mfdeveloper508
