### PR TITLE
Override batch numbers in MergeFiles()

### LINKED ISSUE #867: file: MergeFiles can produce invalid files
ACH Version: `v1.6.2`

**What were you trying to do?**
When calling `MergeFiles(...)` with multiple files you can get an `ach.File` out does not validate. This is from the ordering of input files that are appended to the output file, but done so in an incorrect ordering. 

**What did you expect to see?**
`MergeFiles(..)` should product valid files.

**What did you see?**
`MergeFiles(..)` produced an file which was not valid.

### PR DESCRIPTION
**Pull request by vxio**
Fixes #867

### CODE REVIEW

**Review by adamdecaf — DISMISSED** [review]

File: merge.go [hunk 1]
```diff
@@ -71,9 +71,18 @@ func MergeFiles(files []*File) ([]*File, error) {
 		}
 	}
 
-	// TODO(adam): We should also look at consolidating EntryDetail records inside Batches
+	// Return LOC-maxed files and merged files
+	out := append(fs.locMaxed, fs.outfiles...)
 
-	return append(fs.locMaxed, fs.outfiles...), nil // return LOC-maxed files and merged files
+	// Override batch numbers to ensure they don't collide
```
Comment (adamdecaf) [inline merge.go:78]: Can we document this on the GoDoc?

Comment (vxio) [reply merge.go:78]: Updated that!

**Review by adamdecaf — APPROVED** [review]
