### PR TITLE
Fix ImmediateDestination formatting when BypassDestinationValidation is true

### LINKED ISSUE #814: file-format: the destination field is not properly formatted when the BypassDestination validation option is set
ACH Version: `v1.5.2`

When setting `ach.ValidateOpts{ BypassDestinationValidation: true}`, the Destination field is not properly formatted. A `0` is set between the Origin and Destination fields. We should replace the `0` with a space.

We can reuse the same logic from `ImmediateOriginField()`:
https://github.com/moov-io/ach/blob/master/fileHeader.go#L301-L309

### PR DESCRIPTION
**Pull request by vxio**
Fixes #814 and added tests

### CODE REVIEW

File: fileHeader_test.go [hunk 1]
```diff
@@ -96,17 +96,81 @@ func TestFileHeader__ImmediateOrigin(t *testing.T) {
...
-	if v := trimImmediateOriginLeadingZero("0123456789"); v != "123456789" {
-		t.Errorf("got %q", v)
-	}
-	if v := trimImmediateOriginLeadingZero("0012345678"); v != "012345678" {
-		t.Errorf("got %q", v)
-	}
-	zeros := strings.Repeat("0", 10)
-	if v := trimImmediateOriginLeadingZero(zeros); v != zeros {
-		t.Errorf("got %q", v)
+func TestFileHeader__ImmediateDestination(t *testing.T) {
```
Comment (vxio) [inline fileHeader_test.go:101]: These tests are almost the same as the test above for `ImmediateOrigin` but we're using table-driven tests here for clarity; let me know if I should spin up another issue to convert the tests to match.

File: fileHeader_test.go [hunk 2]
```diff
@@ -96,17 +96,81 @@ func TestFileHeader__ImmediateOrigin(t *testing.T) {
...
+			}
+
+			if v := header.ImmediateDestinationField(); v != tt.expected {
+				t.Errorf("want \"%v\", got \"%v\"", tt.expected, v)
+			}
+		})
+	}
+}
+
+func Test__trimRoutingNumberLeadingZero(t *testing.T) {
```
Comment (vxio) [inline fileHeader_test.go]: These checks used to live in `TestFileHeader__ImmediateOrigin` but I moved them here since the helper function is used for both origin and destination now.

**Review by adamdecaf — DISMISSED** [review]

File: fileHeader_test.go (hunk 1 above)
Comment (adamdecaf) [reply fileHeader_test.go:101]: This nice cleanup, thanks!

File: fileHeader_test.go (hunk 2 above)
Comment (adamdecaf) [reply fileHeader_test.go]: Maybe call it `TestFileHeader__trimRoutingNumberLeadingZero(t *testing.T)` ?

**Review by adamdecaf — APPROVED** [review]
