### PR TITLE
writer: add an option to bypass file validation

### LINKED ISSUE #903: writer: add an option to bypass call to File.Validate()
ACH Version: `1.7.1`

**What were you trying to do?**
Write an invalid ACH file to an underlying writer using `Write(file *File)` 

**What did you expect to see?**
The operation to succeed with no error.

**What did you see?**
The call to `Write(..)` will fail because of a call to `file.Validate()`.

**One use-case would be a system that:**
- reads in an invalid ACH file (`Reader.Read(..)` does not make a call to `File.Validate()`)
- makes minor adjustments like updating the immediate origin
- writes the invalid file out to be forwarded to another system

### PR DESCRIPTION
**Pull request by vxio**
Fixes #903

### CODE REVIEW

File: writer.go [hunk 1]
```diff
@@ -23,15 +23,14 @@ import (
 	"strings"
 )
 
-// A Writer writes an ach.file to a NACHA encoded file.
-//
-// As returned by NewWriter, a Writer writes ach.file structs into
-// NACHA formatted files.
-//
+// Writer writes a File to an io.Writer.
```
Comment (vxio) [inline writer.go:26]: Updated the GoDoc here for clarity. The previous code comments were a bit redundant.

**Review by adamdecaf — APPROVED** [review]
